[versions]
accompanist-permissions = "0.37.3"
accompanist-swiperefresh = "0.36.0"
activity-compose = "1.12.0-alpha09"
androidx-junit = "1.3.0"
appcompat = "1.7.1"
core-ktx = "1.17.0"
desugar_jdk_libs = "2.1.5"
espresso = "3.7.0"
junit = "4.13.2"
kotlin = '2.2.20'
coroutines = "1.10.2"
lifecycle = "2.9.4"
material = "1.13.0"
multidex = "2.0.1"
nav3 = "1.0.0-rc01"
okio = "3.16.2"
retrofit = '3.0.0'
okhttp = "5.3.1"
moshi = '1.15.2'
room = "2.8.3"
metro = "0.7.7"
workmanager = "2.10.5"
agp = "8.13.1"
uiautomator = "2.3.0"
benchmark-macro-junit4 = "1.4.1"
baselineprofile = "1.4.1"
profileinstaller = "1.4.1"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-legacy = "androidx.legacy:legacy-support-v4:1.0.0"
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "workmanager" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version = "1.1.7"}

compose-bom = "androidx.compose:compose-bom:2025.09.01"
compose-materialIcons-core = { module = "androidx.compose.material:material-icons-core" }
compose-materialIcons-extended = { module = "androidx.compose.material:material-icons-extended" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-uiTooling = { module = "androidx.compose.ui:ui-tooling" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-test = { module = "androidx.compose.ui:ui-test-junit4" }
compose-constraintLayout = "androidx.constraintlayout:constraintlayout-compose:1.1.1"

nav3-runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "nav3" }
nav3-ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "nav3" }
nav3-lifecycle = { module = "androidx.lifecycle:lifecycle-viewmodel-navigation3", version = "2.10.0-alpha04" }

kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version = "1.9.0" }

accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist-permissions" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompanist-swiperefresh" }

desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }

kotlin-stdlib-jdk7 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-immutableCollections = "org.jetbrains.kotlinx:kotlinx-collections-immutable:0.4.0"

firebase-bom = "com.google.firebase:firebase-bom:34.6.0"
firebase-crashlytics      = { module = "com.google.firebase:firebase-crashlytics" }
firebase-analytics      = { module = "com.google.firebase:firebase-analytics" }

material = { module = "com.google.android.material:material", version.ref = "material" }

okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
moshi-core = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

timber = "com.jakewharton.timber:timber:5.0.1"

espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "uiautomator" }
androidx-benchmark-macro-junit4 = { group = "androidx.benchmark", name = "benchmark-macro-junit4", version.ref = "benchmark-macro-junit4" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "profileinstaller" }

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
ksp = "com.google.devtools.ksp:2.2.20-2.0.3"
room = { id = "androidx.room", version.ref = "room" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
googleServices = { id = "com.google.gms.google-services", version = "4.4.4" }
firebaseCrashlytics = { id = "com.google.firebase.crashlytics", version = "3.0.6" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version="2.2.21"}
baselineprofile = { id = "androidx.baselineprofile", version.ref = "baselineprofile" }
metro = { id = "dev.zacsweers.metro", version.ref = "metro" }

